logging:
  level:
    org:
      springframework:
        web: info
  file:
    name: ${user.home}/logs/csp/sentinel-dashboard.log
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'

security:
  encode:
    key: faster,2020Ypass

#spring:
#  quartz:
#    # 将任务等保存化到数据库
#    job-store-type: jdbc
#    # 程序结束时会等待quartz相关的内容结束
#    wait-for-jobs-to-complete-on-shutdown: true
#    # QuartzScheduler启动时更新己存在的Job,这样就不用每次修改targetObject后删除qrtz_job_details表对应记录
#    overwrite-existing-jobs: true
#    # 这里居然是个map，搞得智能提示都没有，佛了
#    properties:
#      org:
#        quartz:
#          # scheduler相关
#          scheduler:
#            # scheduler的实例名
#            instanceName: scheduler
#            instanceId: AUTO
#          # 持久化相关
#          jobStore:
#            class: org.quartz.impl.jdbcjobstore.JobStoreTX
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#            # 表示数据库中相关表是QRTZ_开头的
#            tablePrefix: QRTZ_
#            useProperties: false
#            dataSource: qzDS
#          # 线程池相关
#          threadPool:
#            class: org.quartz.simpl.SimpleThreadPool
#            # 线程数
#            threadCount: 10
#            # 线程优先级
#            threadPriority: 5
#            threadsInheritContextClassLoaderOfInitializingThread: true
#          dataSource:
#            qzDS:
#              provider: hikaricp
#              driver: com.mysql.cj.jdbc.Driver
#              url: jdbc:mysql://119.23.71.201:3306/faster?characterEncoding=utf8
#              user: root
#              password: kDfh9GZ?Q(BE
#              maxConnections: 10
